services:
  - type: web
    name: akuko-akowe-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn blog_api.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: "akuko-akowe-api.onrender.com,1dfe-102-88-53-239.ngrok-free.app,localhost"
