services:
  - type: web
    name: chronicle-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn blog_api.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "chronicle-server-f2n9.onrender.com,chronicle-blog.vercel.app,localhost,127.0.0.1,.onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chronicle_db
          property: connectionString
